# Generated by Django 4.1.2 on 2022-10-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='none@none.none', max_length=100),
        ),
    ]
