# Generated by Django 4.1.2 on 2022-10-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_news_alter_feedback_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='news',
            name='public_date',
            field=models.DateField(null=True),
        ),
    ]
